# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

[bot_qqbot_secret]
# プラットフォーム側のキー設定項目です。ここに入力された値は、送信メッセージに誤って含まれた場合、ボットはそれを傍受しようとします。ただし、漏洩を防ぐよう注意してください。
qq_bot_secret = "<Replace me with str value>" # QQ ロボット（公式）の AppSecret。

[bot_qqbot]
# プラットフォーム側の設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
qq_bot_appid = "<Replace me with (int, str) value>" # QQ ロボット（公式）の AppID。
enable = false # このプラットフォームを有効にするかどうか。
qq_private_bot = false # QQ ロボット（公式）を使用する場合、プライベートドメイン ロボットであるかどうか。
qq_bot_enable_send_url = false # QQ ロボット（公式）使用時に、URL 送信を有効にするかどうか。
qq_typing_emoji = 181 # 使用 QQ 相关协议端时，正在处理消息时向消息挂上的回应表情 ID，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api/openapi/emoji/model.html#Emoji
