# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

[bot_aiocqhttp]
# プラットフォーム側の設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
qq_enable_listening_self_message = false # Onebot プロトコルを使用するときに、自己メッセージの監視を有効にするかどうか。
qq_host = "127.0.0.1:8080" # Aiocqhttp WebSocket メインサーバーのアドレス。（Onebot プロトコル側はリバース Websocket 方式を使用して接続する必要があります）
qq_allow_approve_friend = false # Onebot プロトコルを使用するときに、友達リクエストを自動的に承認するかどうか。
qq_allow_approve_group_invite = false # Onebot プロトコルを使用するときに、グループの招待を自動的に受け入れるかどうか。
qq_disable_temp_session = true # Onebot プロトコルを使用するときに、一時セッションを有効にするかどうか。
enable = false # このプラットフォームを有効にするかどうか。
qq_typing_emoji = 181 # 使用 QQ 相关协议端时，正在处理消息时向消息挂上的回应表情 ID，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api/openapi/emoji/model.html#Emoji
qq_limited_emoji = 10060 # 使用 QQ 相关协议端时，消息处理失败时向消息挂上的回应表情 ID，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api/openapi/emoji/model.html#Emoji

[bot_aiocqhttp_secret]
# プラットフォーム側のキー設定項目です。ここに入力された値は、送信メッセージに誤って含まれた場合、ボットはそれを傍受しようとします。ただし、漏洩を防ぐよう注意してください。
qq_access_token = "<Replace me with str value>" # Onebot プロトコルを使用するときに、WebSocket サーバーに接続するための Access Token。
