# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

default_locale = "ja_jp" # デフォルトのセッション ロケール。
config_version = 2 # バージョン番号。機能アップデートに伴い自動的に増加されるので、通常は変更しないでください。

[config]
# 基本的な設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
unloaded_modules = [] # ロードされないモジュールのリスト。このリストに一致するモジュールはロードされない。
