# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。請不要在此處使用 Python 語法。
# 例如：TOML 中的布林值必須是小寫。

default_locale = "zh_tw" # 預設的會話語言環境。
config_version = 2 # 設定檔版本號，將會隨功能更新自動增加，一般情況下請勿修改。

[config]
# 一些基礎的設定部分，此處填寫的值可在訊息中以明文形式顯示。請不要在此部分填寫敏感資訊。
unloaded_modules = [] # 不載入的模組列表，符合到此列表中的模組將不會被載入。
